[[constraint]]
  name = "github.com/sirupsen/logrus"
  tag = "v1.3.0"

[[constraint]]
  name = "github.com/bitrise-io/envman"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/goinp"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  branch = "master"

[[constraint]]
  name = "github.com/json-iterator/go"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-cmp"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

# [prune]
#   go-tests = true
#   unused-packages = true
